version: "3.8"

services:
  # Main development container with all languages
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
      - cargo-cache:/home/vscode/.cargo/registry
      - maven-cache:/home/vscode/.m2
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dev
      - MARIADB_URL=mysql://root:rootpass@mariadb:3306/dev
      - OPENSEARCH_URL=http://opensearch:9200
      - DUCKDB_PATH=/workspace/data/warehouse.duckdb
    ports:
      - "8080:8080" # Spring Boot
      - "8000:8000" # Python/FastAPI
      - "9000:9000" # Rust services
    depends_on:
      - mariadb
      - opensearch
      - postgres
    networks:
      - dev-network

  # MariaDB for transactional data
  mariadb:
    image: mariadb:11.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL for DuckDB metadata and general use
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # OpenSearch for search and analytics
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true # For dev only!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - dev-network
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # OpenSearch Dashboards (optional but useful)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true # For dev only!
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - dev-network

volumes:
  mariadb-data:
  postgres-data:
  opensearch-data:
  cargo-cache:
  maven-cache:

networks:
  dev-network:
    driver: bridge
